name: check mabl cli version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: previous workflow run-id
        id: previous-workflow-run-id
        run: |
          PREV_ID=$(curl -fsSL 'https://api.github.com/repos/tmtmtoo/retry-mabl-cli/actions/runs?per_page=1' | jq -r '.workflow_runs[0].id')
          echo "GITHUB_PREVIOUS_RUN_ID=$PREV_ID" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: mabl-cli-version
          run-id: ${{ env.GITHUB_PREVIOUS_RUN_ID }}

      - name: show mabl-cli latest version
        run: npm info @mablhq/mabl-cli version > latest && cat latest

      - name: compare with previous results
        run: diff mabl-cli-version latest

      - name: hogehoge
        if: failure()
        run: cat mabl-cli-version

      - name: rename
        run: mv latest mabl-cli-version

      - uses: actions/upload-artifact@v4
        with:
          name: mabl-cli-version
          path: mabl-cli-version
