name: check mabl cli version

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/download-artifact@v4
        with:
          name: mabl-cli-version

      - name: show mabl-cli latest version
        if: failure()
        run: npm info @mablhq/mabl-cli version > latest && cat latest

      - name: compare with previous results
        run: diff mabl-cli-version latest

      - name: hogehoge
        if: failure()
        run: cat mabl-cli-version

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: mabl-cli-version
          path: latest
